<a href="https://www.kaggle.com/code/rihamibrahim/datascienceproject-9bf85d-016508?scriptVersionId=176260860" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd 
import numpy as np 
import warnings
warnings.filterwarnings("ignore")

In [2]:
#read data that from 2005 to 2014
accident_data = pd.read_csv('/kaggle/input/uk-accidents-10-years-history-with-many-variables/Accidents0514.csv')
vehicles_data = pd.read_csv('/kaggle/input/uk-accidents-10-years-history-with-many-variables/Vehicles0514.csv')
casualties_data = pd.read_csv('/kaggle/input/uk-accidents-10-years-history-with-many-variables/Casualties0514.csv')

In [3]:
accident_data.shape

(1640597, 32)

In [4]:
accident_data.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,0,1,1,2,2,0,0,1,1,E01002849
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,0,5,4,1,1,0,0,1,1,E01002909
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,0,0,4,1,1,0,0,1,1,E01002857
3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,0,0,1,1,1,0,0,1,1,E01002840
4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,...,0,0,7,1,2,0,0,1,1,E01002863

In [5]:
vehicles_data.shape

(3004425, 22)

In [6]:
vehicles_data.head()

,Accident_Index,Vehicle_Reference,Vehicle_Type,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Location-Restricted_Lane,Junction_Location,Skidding_and_Overturning,Hit_Object_in_Carriageway,Vehicle_Leaving_Carriageway,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,200501BS00001,1,9,0,18,0,0,0,0,0,...,1,15,2,74,10,-1,-1,-1,7,1
1,200501BS00002,1,11,0,4,0,3,0,0,0,...,1,1,1,42,7,8268,2,3,-1,-1
2,200501BS00003,1,11,0,17,0,0,0,4,0,...,1,1,1,35,6,8300,2,5,2,1
3,200501BS00003,2,9,0,2,0,0,0,0,0,...,1,15,1,62,9,1762,1,6,1,1
4,200501BS00004,1,9,0,18,0,0,0,0,0,...,1,15,2,49,8,1769,1,4,2,1

In [7]:
casualties_data.shape

(2216720, 15)

In [8]:
casualties_data.head()

,Accident_Index,Vehicle_Reference,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type
0,200501BS00001,1,1,3,1,37,7,2,1,1,0,0,-1,0,1
1,200501BS00002,1,1,2,1,37,7,3,0,0,0,4,-1,11,1
2,200501BS00003,2,1,1,1,62,9,3,0,0,0,0,-1,9,1
3,200501BS00004,1,1,3,1,30,6,3,5,2,0,0,-1,0,1
4,200501BS00005,1,1,1,1,49,8,3,0,0,0,0,-1,3,-1

In [9]:
# accident_data.replace(-1, 'NaN', inplace=True)
# vehicles_data.replace(-1, 'NaN', inplace=True)
# casualties_data.replace(-1, 'NaN', inplace=True)

In [10]:
# Merge Accidents and Casualties dataframes on 'Accident_Index'
final_data = pd.merge(accident_data, casualties_data, on='Accident_Index')
# Merge df with Vehicles dataframe on 'Accident_Index'
final_data = pd.merge(final_data, vehicles_data, on='Accident_Index')
#remove Accidents, Casualties, and Vehicles dataframes
del accident_data, casualties_data, vehicles_data

In [ ]:
# final_data = pd.merge(accident_data, casualties_data, on='Accident_Index', how='left')
# final_data = pd.merge(final_data, vehicles_data, on='Accident_Index', how='left')

In [11]:
final_data.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,1,15,2,74,10,-1,-1,-1,7,1
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,1,1,1,42,7,8268,2,3,-1,-1
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,1,1,1,35,6,8300,2,5,2,1
3,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,1,15,1,62,9,1762,1,6,1,1
4,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,1,15,2,49,8,1769,1,4,2,1

In [12]:
print(final_data.columns)

Index(['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR',
       'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
       'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)',
       '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Junction_Control', '2nd_Road_Class',
       '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Conditions_at_Site', 'Carriageway_Hazards',
       'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'LSOA_of_Accident_Location', 'Vehicle_Reference_x',
       'Casualty_Reference', 'Casualty_Class', 'Sex_of_Casualty',
       'Age_of_Casualty', 'Age_Band_of_Casualty', 'Casualty_Severity',
       'Pedestrian_Location', 'Pedestrian_Movement', 'Car_Passenger',
       'Bus_or_Coach_Passenger', 'Pedestrian_Road_Maintenance_Worker',
       'Casualty_Type', 'Casualty_Home_Area_Type', 'Vehicle_Reference_y',
       'Vehicle_Type', 'Towing_and_Articulation', 'Vehicle_Manoeuvre',
       'Vehicle_Location-Restricted_Lane', 'Junction_Location',
       'Skidding_and_Overturning', 'Hit_Object_in_Carriageway',
       'Vehicle_Leaving_Carriageway', 'Hit_Object_off_Carriageway',
       '1st_Point_of_Impact', 'Was_Vehicle_Left_Hand_Drive?',
       'Journey_Purpose_of_Driver', 'Sex_of_Driver', 'Age_of_Driver',
       'Age_Band_of_Driver', 'Engine_Capacity_(CC)', 'Propulsion_Code',
       'Age_of_Vehicle', 'Driver_IMD_Decile', 'Driver_Home_Area_Type'],
      dtype='object')

In [13]:
import pandas as pd

column_names = ['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR',
       'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
       'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)',
       '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit',
       'Junction_Detail', 'Junction_Control', '2nd_Road_Class',
       '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Conditions_at_Site', 'Carriageway_Hazards',
       'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'LSOA_of_Accident_Location', 'Vehicle_Reference_x',
       'Casualty_Reference', 'Casualty_Class', 'Sex_of_Casualty',
       'Age_of_Casualty', 'Age_Band_of_Casualty', 'Casualty_Severity',
       'Pedestrian_Location', 'Pedestrian_Movement', 'Car_Passenger',
       'Bus_or_Coach_Passenger', 'Pedestrian_Road_Maintenance_Worker',
       'Casualty_Type', 'Casualty_Home_Area_Type', 'Vehicle_Reference_y',
       'Vehicle_Type', 'Towing_and_Articulation', 'Vehicle_Manoeuvre',
       'Vehicle_Location-Restricted_Lane', 'Junction_Location',
       'Skidding_and_Overturning', 'Hit_Object_in_Carriageway',
       'Vehicle_Leaving_Carriageway', 'Hit_Object_off_Carriageway',
       '1st_Point_of_Impact', 'Was_Vehicle_Left_Hand_Drive?',
       'Journey_Purpose_of_Driver', 'Sex_of_Driver', 'Age_of_Driver',
       'Age_Band_of_Driver', 'Engine_Capacity_(CC)', 'Propulsion_Code',
       'Age_of_Vehicle', 'Driver_IMD_Decile', 'Driver_Home_Area_Type']

# Convert the list to a pandas Series
column_series = pd.Series(column_names)

# Check for duplicates
duplicates = column_series[column_series.duplicated()]
if not duplicates.empty:
    print("Duplicated column names:")
    print(duplicates)
else:
    print("No duplicated column names found.")

No duplicated column names found.

In [14]:
df = final_data.copy()

In [15]:
df.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,1,15,2,74,10,-1,-1,-1,7,1
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,1,1,1,42,7,8268,2,3,-1,-1
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,1,1,1,35,6,8300,2,5,2,1
3,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,1,15,1,62,9,1762,1,6,1,1
4,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,1,15,2,49,8,1769,1,4,2,1

In [16]:
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.5/96.5 kB 1.1 MB/s eta 0:00:00a 0:00:010m
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

In [17]:
df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [18]:
# # Read the Excel file and sheet
# casualty_severity = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Accident Severity")

# # Perform left join
# df = pd.merge(df, casualty_severity, left_on="Casualty_Severity", right_on="code", how="left")

# # Rename the column
# df.rename(columns={"label": "Casualty_Outcome"}, inplace=True)

# # Optionally, remove the temporary variable
# del casualty_severity

# Read the Excel file and sheet
casualty_severity = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Accident Severity")

# Perform left join
df = pd.merge(df, casualty_severity, left_on="Casualty_Severity", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Casualty_Outcome"}, inplace=True)

# Optionally, remove the temporary variable
del casualty_severity

In [19]:
# Read the Excel file and sheet
location_code = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Police Force")

# Perform left join
df = pd.merge(df, location_code, left_on="Police_Force", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Location"}, inplace=True)

# Optionally, remove the temporary variable
del location_code

In [20]:
# Read the Excel file and sheet
junction_type = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Junction Detail")

# Perform left join
df = pd.merge(df, junction_type, left_on="Junction_Detail", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Junction"}, inplace=True)

# Optionally, remove the temporary variable
del junction_type

In [21]:
# Read the Excel file and sheet
light_conditions = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Light Conditions")

# Perform left join with specified suffixes
df = pd.merge(df, light_conditions, left_on="Light_Conditions", right_on="code", how="left", suffixes=('_main', '_light'))

# Rename the column
df.rename(columns={"label_light": "Lighting"}, inplace=True)

# Optionally, remove the temporary variable
del light_conditions

In [22]:
# Read the weather conditions data
weather_conditions = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Weather")

# Perform left join to map weather condition codes to labels
df = pd.merge(df, weather_conditions, left_on="Weather_Conditions", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Weather"}, inplace=True)

# Optionally, remove the temporary variable
del weather_conditions

In [23]:
# Read the surface conditions data
surface_conditions = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Road Surface")

# Perform left join to map road surface condition codes to labels
df = pd.merge(df, surface_conditions, left_on="Road_Surface_Conditions", right_on="code", how="left", suffixes=('_left', '_right'))

# Rename the column
df.rename(columns={"label": "Surface"}, inplace=True)

# Optionally, remove the temporary variable
del surface_conditions

In [24]:
vehicle_type = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Vehicle Type")

# Perform left join to map vehicle type codes to labels
df = pd.merge(df, vehicle_type, left_on="Vehicle_Type", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Vehicle"}, inplace=True)

# Optionally, remove the temporary variable
del vehicle_type

In [25]:
# Check if df contains any columns named "code" or "label"
if "code" in df.columns or "label" in df.columns:
    # If so, rename or drop these columns
    df.rename(columns={"code": "code_df", "label": "label_df"}, inplace=True)
    # Or you can drop them if they are not needed
    # df.drop(columns=["code", "label"], inplace=True)

# Read the vehicle manoeuvre data
vehicle_manoeuvre = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Vehicle Manoeuvre")

# Perform left join to map vehicle manoeuvre codes to labels
df = pd.merge(df, vehicle_manoeuvre, left_on="Vehicle_Manoeuvre", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Manoeuvre"}, inplace=True)

# Optionally, remove the temporary variable
del vehicle_manoeuvre

In [26]:
# Check if df contains any columns named "code" or "label"
if "code" in df.columns or "label" in df.columns:
    # If so, rename or drop these columns
    df.rename(columns={"code": "code_df", "label": "label_df"}, inplace=True)
    # Or you can drop them if they are not needed
    # df.drop(columns=["code", "label"], inplace=True)

# Read the skidding data
skidding = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Skidding and Overturning")

# Perform left join to map skidding codes to labels
df = pd.merge(df, skidding, left_on="Skidding_and_Overturning", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Skidding"}, inplace=True)

# Optionally, remove the temporary variable
del skidding

In [27]:
# Check if df contains any columns named "code" or "label"
if "code" in df.columns or "label" in df.columns:
    # If so, rename or drop these columns
    df.rename(columns={"code": "code_df", "label": "label_df"}, inplace=True)
    # Or you can drop them if they are not needed
    # df.drop(columns=["code", "label"], inplace=True)

# Read the journey purpose data
journey_purpose = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Journey Purpose")

# Perform left join to map journey purpose codes to labels
df = pd.merge(df, journey_purpose, left_on="Journey_Purpose_of_Driver", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Journey"}, inplace=True)

# Optionally, remove the temporary variable
del journey_purpose

In [28]:
# Check if df contains any columns named "code" or "label"
if "code" in df.columns or "label" in df.columns:
    # If so, rename or drop these columns
    df.rename(columns={"code": "code_df", "label": "label_df"}, inplace=True)
    # Or you can drop them if they are not needed
    # df.drop(columns=["code", "label"], inplace=True)

# Read the age band data
age_band = pd.read_excel("/kaggle/input/uk-accidents-10-years-history-with-many-variables/Road-Accident-Safety-Data-Guide.xls", sheet_name="Age Band")

# Perform left join to map age band codes to labels
df = pd.merge(df, age_band, left_on="Age_Band_of_Driver", right_on="code", how="left")

# Rename the column
df.rename(columns={"label": "Age_Band"}, inplace=True)

# Optionally, remove the temporary variable
del age_band

In [29]:
df.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,code_df,Vehicle,code_df,Manoeuvre,code_df,Skidding,code_df,Journey,code,Age_Band
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,9,Car,18,Going ahead other,0,NaN,15,Other/Not known (2005-10),10,66 - 75
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,11,Bus or coach (17 or more pass seats),4,Slowing or stopping,0,NaN,1,Journey as part of work,7,36 - 45
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,11,Bus or coach (17 or more pass seats),17,Going ahead right-hand bend,0,NaN,1,Journey as part of work,6,26 - 35
3,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,9,Car,2,Parked,0,NaN,15,Other/Not known (2005-10),9,56 - 65
4,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,9,Car,18,Going ahead other,0,NaN,15,Other/Not known (2005-10),8,46 - 55

In [30]:
columns_with_minus_one = df.columns[(df == -1).any()].tolist()

print("Columns containing -1:")
print(columns_with_minus_one)

Columns containing -1:
['Longitude', '1st_Road_Number', 'Junction_Detail', 'Junction_Control', '2nd_Road_Class', '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities', 'Weather_Conditions', 'Road_Surface_Conditions', 'Special_Conditions_at_Site', 'Carriageway_Hazards', 'Did_Police_Officer_Attend_Scene_of_Accident', 'Sex_of_Casualty', 'Age_of_Casualty', 'Age_Band_of_Casualty', 'Pedestrian_Location', 'Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger', 'Pedestrian_Road_Maintenance_Worker', 'Casualty_Home_Area_Type', 'Vehicle_Type', 'Towing_and_Articulation', 'Vehicle_Manoeuvre', 'Vehicle_Location-Restricted_Lane', 'Junction_Location', 'Skidding_and_Overturning', 'Hit_Object_in_Carriageway', 'Vehicle_Leaving_Carriageway', 'Hit_Object_off_Carriageway', '1st_Point_of_Impact', 'Was_Vehicle_Left_Hand_Drive?', 'Journey_Purpose_of_Driver', 'Sex_of_Driver', 'Age_of_Driver', 'Age_Band_of_Driver', 'Engine_Capacity_(CC)', 'Propulsion_Code', 'Age_of_Vehicle', 'Driver_IMD_Decile', 'Driver_Home_Area_Type', 'code_main', 'code_left', 'code_right', 'code_df', 'code_df', 'code_df', 'code_df', 'code']

In [31]:
df['Casualty_Outcome']

0          Serious
1           Slight
2           Slight
3           Slight
4           Slight
            ...
4287588    Serious
4287589     Slight
4287590     Slight
4287591     Slight
4287592     Slight
Name: Casualty_Outcome, Length: 4287593, dtype: object

In [32]:
df_cat_copy = df.copy()

**Eliminating extra variables**

In [33]:
# Drop specified columns from the DataFrame
columns_to_drop = ["Driver_Home_Area_Type", "Driver_IMD_Decile", "Propulsion_Code", "Age_Band_of_Driver", 
                   "1st_Point_of_Impact", "Hit_Object_off_Carriageway", "Vehicle_Leaving_Carriageway", 
                   "Hit_Object_in_Carriageway", "Junction_Location", "Vehicle_Location-Restricted_Lane", 
                   "Towing_and_Articulation", "Pedestrian_Road_Maintenance_Worker", "Pedestrian_Movement", 
                   "Pedestrian_Location", "Casualty_Reference", "LSOA_of_Accident_Location", 
                   "Did_Police_Officer_Attend_Scene_of_Accident", "Urban_or_Rural_Area", "Carriageway_Hazards", 
                   "Pedestrian_Crossing-Physical_Facilities", "Pedestrian_Crossing-Human_Control", 
                   "2nd_Road_Class", "2nd_Road_Number", "Junction_Control", "Junction_Detail", 
                   "Local_Authority_(Highway)"]

accidents_data_cleanup = ['Longitude','Time','Speed_limit', 'Junction_Detail', 'Light_Conditions', 'Road_Type',
                          'Did_Police_Officer_Attend_Scene_of_Accident','Weather_Conditions', 
                          'Road_Surface_Conditions', 'Special_Conditions_at_Site','Carriageway_Hazards', 
                          'Urban_or_Rural_Area', 'Accident_Severity', '1st_Road_Class', 
                          'Pedestrian_Crossing-Human_Control', 
                          'Pedestrian_Crossing-Physical_Facilities', 
                          'Police_Force','Vehicle_Type', 'Sex_of_Driver', 'Age_of_Driver', 
                          'Vehicle_Manoeuvre']

df_cat_copy = df_cat_copy.drop(columns=columns_to_drop)

In [35]:
columns_to_drop = ['code','code_df']

df_cat_copy = df_cat_copy.drop(columns=columns_to_drop)

In [37]:
columns_to_drop = ['code_x','code_y','code_main','code_light','code_left','code_right']

df_cat_copy = df_cat_copy.drop(columns=columns_to_drop)

In [41]:
df_cat_copy.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Location,Junction,label_x,label_y,Surface,Vehicle,Manoeuvre,Skidding,Journey,Age_Band
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,Metropolitan Police,Not at junction or within 20 metres,Daylight,Raining no high winds,Wet or damp,Car,Going ahead other,NaN,Other/Not known (2005-10),66 - 75
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,Metropolitan Police,Crossroads,Darkness - lights lit,Fine no high winds,Dry,Bus or coach (17 or more pass seats),Slowing or stopping,NaN,Journey as part of work,36 - 45
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,Metropolitan Police,Not at junction or within 20 metres,Darkness - lights lit,Fine no high winds,Dry,Bus or coach (17 or more pass seats),Going ahead right-hand bend,NaN,Journey as part of work,26 - 35
3,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,Metropolitan Police,Not at junction or within 20 metres,Darkness - lights lit,Fine no high winds,Dry,Car,Parked,NaN,Other/Not known (2005-10),56 - 65
4,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,Metropolitan Police,Not at junction or within 20 metres,Daylight,Fine no high winds,Dry,Car,Going ahead other,NaN,Other/Not known (2005-10),46 - 55

In [42]:
columns_with_minus_one = df_cat_copy.columns[(df_cat_copy == -1).any()].tolist()

print("Columns containing -1:")
print(columns_with_minus_one)

Columns containing -1:
['Longitude', '1st_Road_Number', 'Weather_Conditions', 'Road_Surface_Conditions', 'Special_Conditions_at_Site', 'Sex_of_Casualty', 'Age_of_Casualty', 'Age_Band_of_Casualty', 'Car_Passenger', 'Bus_or_Coach_Passenger', 'Casualty_Home_Area_Type', 'Vehicle_Type', 'Vehicle_Manoeuvre', 'Skidding_and_Overturning', 'Was_Vehicle_Left_Hand_Drive?', 'Journey_Purpose_of_Driver', 'Sex_of_Driver', 'Age_of_Driver', 'Engine_Capacity_(CC)', 'Age_of_Vehicle']

In [43]:
df_cat_copy.replace(-1, 'NaN', inplace=True)
df_cat_copy.replace(-1, 'NaN', inplace=True)
df_cat_copy.replace(-1, 'NaN', inplace=True)

In [44]:
columns_with_minus_one = df_cat_copy.columns[(df_cat_copy == -1).any()].tolist()

print("Columns containing -1:")
print(columns_with_minus_one)

Columns containing -1:
[]

In [45]:
df_cat_copy.columns

Index(['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR',
       'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity',
       'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week',
       'Time', 'Local_Authority_(District)', '1st_Road_Class',
       '1st_Road_Number', 'Road_Type', 'Speed_limit', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Conditions_at_Site', 'Vehicle_Reference_x', 'Casualty_Class',
       'Sex_of_Casualty', 'Age_of_Casualty', 'Age_Band_of_Casualty',
       'Casualty_Severity', 'Car_Passenger', 'Bus_or_Coach_Passenger',
       'Casualty_Type', 'Casualty_Home_Area_Type', 'Vehicle_Reference_y',
       'Vehicle_Type', 'Vehicle_Manoeuvre', 'Skidding_and_Overturning',
       'Was_Vehicle_Left_Hand_Drive?', 'Journey_Purpose_of_Driver',
       'Sex_of_Driver', 'Age_of_Driver', 'Engine_Capacity_(CC)',
       'Age_of_Vehicle', 'Casualty_Outcome', 'Location', 'Junction', 'label_x',
       'label_y', 'Surface', 'Vehicle', 'Manoeuvre', 'Skidding', 'Journey',
       'Age_Band'],
      dtype='object')

In [46]:
df_cat_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4287593 entries, 0 to 4287592
Data columns (total 52 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Accident_Index                object
 1   Location_Easting_OSGR         float64
 2   Location_Northing_OSGR        float64
 3   Longitude                     object
 4   Latitude                      float64
 5   Police_Force                  int64
 6   Accident_Severity             int64
 7   Number_of_Vehicles            int64
 8   Number_of_Casualties          int64
 9   Date                          object
 10  Day_of_Week                   int64
 11  Time                          object
 12  Local_Authority_(District)    int64
 13  1st_Road_Class                int64
 14  1st_Road_Number               object
 15  Road_Type                     int64
 16  Speed_limit                   int64
 17  Light_Conditions              int64
 18  Weather_Conditions            object
 19  Road_Surface_Conditions       object
 20  Special_Conditions_at_Site    object
 21  Vehicle_Reference_x           int64
 22  Casualty_Class                int64
 23  Sex_of_Casualty               object
 24  Age_of_Casualty               object
 25  Age_Band_of_Casualty          object
 26  Casualty_Severity             int64
 27  Car_Passenger                 object
 28  Bus_or_Coach_Passenger        object
 29  Casualty_Type                 int64
 30  Casualty_Home_Area_Type       object
 31  Vehicle_Reference_y           int64
 32  Vehicle_Type                  object
 33  Vehicle_Manoeuvre             object
 34  Skidding_and_Overturning      object
 35  Was_Vehicle_Left_Hand_Drive?  object
 36  Journey_Purpose_of_Driver     object
 37  Sex_of_Driver                 object
 38  Age_of_Driver                 object
 39  Engine_Capacity_(CC)          object
 40  Age_of_Vehicle                object
 41  Casualty_Outcome              object
 42  Location                      object
 43  Junction                      object
 44  label_x                       object
 45  label_y                       object
 46  Surface                       object
 47  Vehicle                       object
 48  Manoeuvre                     object
 49  Skidding                      object
 50  Journey                       object
 51  Age_Band                      object
dtypes: float64(3), int64(15), object(34)
memory usage: 1.7+ GB

In [48]:
df_cat_copy['Weather_Conditions']

0          2
1          1
2          1
3          1
4          1
          ..
4287588    2
4287589    1
4287590    1
4287591    1
4287592    1
Name: Weather_Conditions, Length: 4287593, dtype: object

In [52]:
col_drop =['Journey_Purpose_of_Driver','Skidding_and_Overturning','Vehicle_Manoeuvre','Road_Surface_Conditions','Weather_Conditions','Light_Conditions','Casualty_Severity']
df_cat_copy = df_cat_copy.drop(columns=col_drop)

In [59]:
# col_drop =['Vehicle_Type']
# df_cat_copy = df_cat_copy.drop(columns=col_drop)
#df_cat_copy.rename(columns={'Location': 'Police_force'}, inplace=True)
df_cat_copy.rename(columns={'label_x': 'Light_conditions'}, inplace=True)
df_cat_copy.rename(columns={'label_y': 'Weather_conditions'}, inplace=True)
df_cat_copy.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,...,Police_force,Junction,Light_conditions,Weather_conditions,Surface,Vehicle,Manoeuvre,Skidding,Journey,Age_Band
0,200501BS00001,525680.0,178240.0,-0.19117,51.489096,2,1,1,04/01/2005,3,...,Metropolitan Police,Not at junction or within 20 metres,Daylight,Raining no high winds,Wet or damp,Car,Going ahead other,NaN,Other/Not known (2005-10),66 - 75
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,3,1,1,05/01/2005,4,...,Metropolitan Police,Crossroads,Darkness - lights lit,Fine no high winds,Dry,Bus or coach (17 or more pass seats),Slowing or stopping,NaN,Journey as part of work,36 - 45
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,3,2,1,06/01/2005,5,...,Metropolitan Police,Not at junction or within 20 metres,Darkness - lights lit,Fine no high winds,Dry,Bus or coach (17 or more pass seats),Going ahead right-hand bend,NaN,Journey as part of work,26 - 35
3,200501BS00003,524520.0,182240.0,-0.206458,51.525301,3,2,1,06/01/2005,5,...,Metropolitan Police,Not at junction or within 20 metres,Darkness - lights lit,Fine no high winds,Dry,Car,Parked,NaN,Other/Not known (2005-10),56 - 65
4,200501BS00004,526900.0,177530.0,-0.173862,51.482442,3,1,1,07/01/2005,6,...,Metropolitan Police,Not at junction or within 20 metres,Daylight,Fine no high winds,Dry,Car,Going ahead other,NaN,Other/Not known (2005-10),46 - 55

# **Data Cleaning**

**Dealing with missing values**

In [64]:
# Check for missing values in the entire DataFrame
missing_values = df_cat_copy.isnull()

# Count the number of missing values in each column
missing_counts = df_cat_copy.isnull().sum()

# Calculate the percentage of missing values in each column
missing_percentages = (df_cat_copy.isnull().sum() / len(df_cat_copy)) * 100

# Print the results
print("Missing value counts:")
print(missing_counts)
print("\nMissing value percentages:")
print(missing_percentages)

# print("\nMissing values per column:")
# print(final_data.isnull().sum())

Missing value counts:
Accident_Index                        0
Location_Easting_OSGR               256
Location_Northing_OSGR              256
Longitude                           256
Latitude                            256
Accident_Severity                     0
Number_of_Vehicles                    0
Number_of_Casualties                  0
Date                                  0
Day_of_Week                           0
Time                                264
Local_Authority_(District)            0
1st_Road_Class                        0
1st_Road_Number                       0
Road_Type                             0
Speed_limit                           0
Special_Conditions_at_Site            0
Vehicle_Reference_x                   0
Casualty_Class                        0
Sex_of_Casualty                       0
Age_of_Casualty                       0
Age_Band_of_Casualty                  0
Car_Passenger                         0
Bus_or_Coach_Passenger                0
Casualty_Type                         0
Casualty_Home_Area_Type               0
Vehicle_Reference_y                   0
Was_Vehicle_Left_Hand_Drive?          0
Sex_of_Driver                         0
Age_of_Driver                         0
Engine_Capacity_(CC)                  0
Age_of_Vehicle                        0
Casualty_Outcome                      0
Police_force                          0
Junction                              0
Light_conditions                      0
Weather_conditions                    0
Surface                               0
Vehicle                               0
Manoeuvre                             0
Skidding                        3671406
Journey                               0
Age_Band                              0
dtype: int64

Missing value percentages:
Accident_Index                   0.000000
Location_Easting_OSGR            0.005971
Location_Northing_OSGR           0.005971
Longitude                        0.005971
Latitude                         0.005971
Accident_Severity                0.000000
Number_of_Vehicles               0.000000
Number_of_Casualties             0.000000
Date                             0.000000
Day_of_Week                      0.000000
Time                             0.006157
Local_Authority_(District)       0.000000
1st_Road_Class                   0.000000
1st_Road_Number                  0.000000
Road_Type                        0.000000
Speed_limit                      0.000000
Special_Conditions_at_Site       0.000000
Vehicle_Reference_x              0.000000
Casualty_Class                   0.000000
Sex_of_Casualty                  0.000000
Age_of_Casualty                  0.000000
Age_Band_of_Casualty             0.000000
Car_Passenger                    0.000000
Bus_or_Coach_Passenger           0.000000
Casualty_Type                    0.000000
Casualty_Home_Area_Type          0.000000
Vehicle_Reference_y              0.000000
Was_Vehicle_Left_Hand_Drive?     0.000000
Sex_of_Driver                    0.000000
Age_of_Driver                    0.000000
Engine_Capacity_(CC)             0.000000
Age_of_Vehicle                   0.000000
Casualty_Outcome                 0.000000
Police_force                     0.000000
Junction                         0.000000
Light_conditions                 0.000000
Weather_conditions               0.000000
Surface                          0.000000
Vehicle                          0.000000
Manoeuvre                        0.000000
Skidding                        85.628603
Journey                          0.000000
Age_Band                         0.000000
dtype: float64

In [65]:
# Remove rows with missing values
df_cat_copy_cleaned = df_cat_copy.dropna()

# Remove columns with missing values
df_cat_copy_cleaned = df_cat_copy.dropna(axis=1)

In [66]:
df_cat_copy_cleaned.isnull().sum()

Accident_Index                  0
Accident_Severity               0
Number_of_Vehicles              0
Number_of_Casualties            0
Date                            0
Day_of_Week                     0
Local_Authority_(District)      0
1st_Road_Class                  0
1st_Road_Number                 0
Road_Type                       0
Speed_limit                     0
Special_Conditions_at_Site      0
Vehicle_Reference_x             0
Casualty_Class                  0
Sex_of_Casualty                 0
Age_of_Casualty                 0
Age_Band_of_Casualty            0
Car_Passenger                   0
Bus_or_Coach_Passenger          0
Casualty_Type                   0
Casualty_Home_Area_Type         0
Vehicle_Reference_y             0
Was_Vehicle_Left_Hand_Drive?    0
Sex_of_Driver                   0
Age_of_Driver                   0
Engine_Capacity_(CC)            0
Age_of_Vehicle                  0
Casualty_Outcome                0
Police_force                    0
Junction                        0
Light_conditions                0
Weather_conditions              0
Surface                         0
Vehicle                         0
Manoeuvre                       0
Journey                         0
Age_Band                        0
dtype: int64

**Eliminating Duplicates**

In [71]:
df_cat_copy_cleaned.shape

(4287593, 37)

In [70]:
# Check for duplicated rows
duplicated_rows = df_cat_copy_cleaned.duplicated()

# Select rows that are duplicated
duplicated = df_cat_copy_cleaned[duplicated_rows]

# Print duplicated data
print("Duplicated rows:")
print(duplicated)

Duplicated rows:
        Accident_Index  Accident_Severity  Number_of_Vehicles  \
11       200501BS00009                  3                   1
1179     200501BS70618                  3                   2
1180     200501BS70618                  3                   2
1562     200501CP00040                  2                   2
1563     200501CP00040                  2                   2
...                ...                ...                 ...
4285851  201497UA02306                  2                   2
4286201  201497UC01506                  3                   2
4286202  201497UC01506                  3                   2
4286252  201497UC02112                  3                   1
4287406  2014984112714                  2                   1

         Number_of_Casualties        Date  Day_of_Week  \
11                          2  14/01/2005            6
1179                        4  17/10/2005            2
1180                        4  17/10/2005            2
1562                        4  07/03/2005            2
1563                        4  07/03/2005            2
...                       ...         ...          ...
4285851                     3  16/06/2014            2
4286201                     3  17/06/2014            3
4286202                     3  17/06/2014            3
4286252                     2  13/12/2014            7
4287406                     4  06/04/2014            1

         Local_Authority_(District)  1st_Road_Class 1st_Road_Number  \
11                               12               3             315
1179                             12               3            3218
1180                             12               3            3218
1562                            570               3              40
1563                            570               3              40
...                             ...             ...             ...
4285851                         931               6               0
4286201                         919               3             736
4286202                         919               3             736
4286252                         919               3             735
4287406                         917               5              83

         Road_Type  ...  Casualty_Outcome           Police_force  \
11               3  ...            Slight    Metropolitan Police
1179             6  ...            Slight    Metropolitan Police
1180             6  ...            Slight    Metropolitan Police
1562             1  ...           Serious         City of London
1563             1  ...           Serious         City of London
...            ...  ...               ...                    ...
4285851          6  ...           Serious            Strathclyde
4286201          6  ...            Slight            Strathclyde
4286202          6  ...            Slight            Strathclyde
4286252          2  ...            Slight            Strathclyde
4287406          6  ...            Slight  Dumfries and Galloway

                                    Junction       Light_conditions  \
11       Not at junction or within 20 metres               Daylight
1179                 T or staggered junction               Daylight
1180                 T or staggered junction               Daylight
1562                              Roundabout  Darkness - lights lit
1563                              Roundabout  Darkness - lights lit
...                                      ...                    ...
4285851                           Crossroads               Daylight
4286201              T or staggered junction               Daylight
4286202              T or staggered junction               Daylight
4286252              T or staggered junction  Darkness - lights lit
4287406  Not at junction or within 20 metres               Daylight

            Weather_conditions       Surface                Vehicle  \
11          Fine no high winds           Dry                    Car
1179        Fine no high winds           Dry                    Car
1180        Fine no high winds           Dry                    Car
1562     Raining no high winds   Wet or damp                    Car
1563     Raining no high winds   Wet or damp  Taxi/Private hire car
...                        ...           ...                    ...
4285851     Fine no high winds           Dry                    Car
4286201     Fine no high winds           Dry                    Car
4286202     Fine no high winds           Dry                    Car
4286252                  Other  Frost or ice  Taxi/Private hire car
4287406  Raining no high winds   Wet or damp                    Car

                           Manoeuvre                      Journey  \
11                 Going ahead other    Other/Not known (2005-10)
1179             Slowing or stopping    Other/Not known (2005-10)
1180               Going ahead other    Other/Not known (2005-10)
1562     Going ahead right-hand bend    Other/Not known (2005-10)
1563                    Turning left      Journey as part of work
...                              ...                          ...
4285851            Going ahead other                    Not known
4286201                Turning right      Journey as part of work
4286202            Going ahead other  Taking pupil to/from school
4286252            Going ahead other      Journey as part of work
4287406   Going ahead left-hand bend                    Not known

                             Age_Band
11                            66 - 75
1179                          26 - 35
1180     Data missing or out of range
1562                          36 - 45
1563                          36 - 45
...                               ...
4285851                       56 - 65
4286201                       56 - 65
4286202                       26 - 35
4286252                       46 - 55
4287406                       16 - 20

[15503 rows x 37 columns]

In [72]:
# Drop duplicate rows
df_cat_copy_cleaned.drop_duplicates(inplace=True)

In [73]:
df_cat_copy_cleaned.shape

(4272090, 37)

detect and remove outliers

In [ ]:
import cufflinks as cf
import plotly.offline as pyo

# Identify numerical columns
numerical_columns = df.select_dtypes(include=['number']).columns

# Enable the offline mode for Plotly
pyo.init_notebook_mode(connected=True)

# Visualize the distribution of numerical columns using box plots
df[numerical_columns].iplot(kind='box')

In [ ]:
# import dataset
accidents = pd.read_csv("/kaggle/input/dataset0/accidents.csv")

# take a look at first entries
accidents.head()

In [ ]:
accidents.info()

In [ ]:
# number of rows by number of columns
accidents.shape

In [ ]:
# check for 'NaN' values
accidents.isnull().sum()

In [ ]:
# Option 1: Remove rows with missing values
accidents_cleaned = accidents.dropna()

In [ ]:
# Option 2: Impute missing values (e.g., fill with mean, median, mode)
numeric_columns = accidents.select_dtypes(include=['float64', 'int64']).columns
accidents_imputed = accidents.copy()
for column in numeric_columns:
    accidents_imputed[column] = accidents[column].fillna(accidents[column].mean())

In [ ]:
# Option 3: Impute missing values using more advanced techniques (e.g., predictive modeling)
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
accidents_imputed_sklearn = accidents.copy()
accidents_imputed_sklearn[numeric_columns] = imputer.fit_transform(accidents[numeric_columns])

In [ ]:
# After handling missing values, you can save the cleaned dataset to a new file
accidents_cleaned.to_csv("accidents_cleaned.csv", index=False)
accidents_imputed.to_csv("accidents_imputed.csv", index=False)
accidents_imputed_sklearn.to_csv("accidents_imputed_sklearn.csv", index=False)

In [ ]:
# Check the columns in the dataset
print("Original columns:\n", accidents.columns)

In [ ]:
# List of columns to keep (modify this list based on your requirements)
columns_to_keep = ['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude', 'Latitude', 'Police_Force', 'Accident_Severity', 'Number_of_Vehicles', 'Number_of_Casualties', 'Date', 'Day_of_Week', 'Time', 'Local_Authority_(District)', 'Local_Authority_(Highway)', '1st_Road_Class', '1st_Road_Number', 'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control', '2nd_Road_Class', '2nd_Road_Number', 'Pedestrian_Crossing-Human_Control', 'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions', 'Weather_Conditions', 'Road_Surface_Conditions', 'Special_Conditions_at_Site', 'Carriageway_Hazards', 'Urban_or_Rural_Area', 'Did_Police_Officer_Attend_Scene_of_Accident', 'LSOA_of_Accident_Location']

In [ ]:
# Keep only the selected columns
print("Column names in the dataset:\n", accidents.columns)

In [ ]:
# Check the columns after selection
print("Selected columns:\n", accidents.columns)

In [ ]:
# After eliminating extra variables, you can save the updated dataset to a new file
accidents.to_csv("accidents_columns.csv", index=False)

In [ ]:

# Check the shape of the dataset before removing duplicates
print("Shape of the dataset before removing duplicates:", accidents.shape)

In [ ]:
# Remove duplicates
accidents_no_duplicates = accidents.drop_duplicates()

In [ ]:
# Check the shape of the dataset after removing duplicates
print("Shape of the dataset after removing duplicates:", accidents_no_duplicates.shape)

In [ ]:

# Optionally, you can save the dataset without duplicates to a new file
accidents_no_duplicates.to_csv("accidents_no_duplicates.csv", index=False)

In [ ]:
import cufflinks as cf
import plotly.offline

In [ ]:
# Use Cufflinks with Plotly in offline mode
cf.go_offline()

# Create a box plot to visualize the distribution of a numeric variable
# For example, let's use the 'Number_of_Vehicles' column
accidents['Number_of_Vehicles'].iplot(kind='box', title='Box Plot of Number of Vehicles')

In [ ]:
# Detect and remove outliers based on a threshold
# For example, let's remove outliers for the 'Number_of_Vehicles' column using the Interquartile Range (IQR) method
Q1 = accidents['Number_of_Vehicles'].quantile(0.25)
Q3 = accidents['Number_of_Vehicles'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [ ]:
# Remove outliers
accidents_no_outliers = accidents[(accidents['Number_of_Vehicles'] >= lower_bound) & (accidents['Number_of_Vehicles'] <= upper_bound)]

In [ ]:
#Check the shape of the dataset after removing outliers
print("Shape of the dataset after removing outliers:", accidents_no_outliers.shape)

# Optional: Create a box plot after removing outliers to verify
accidents_no_outliers['Number_of_Vehicles'].iplot(kind='box', title='Box Plot of Number of Vehicles (Without Outliers)')

فاصل